## План ноутбука

1. Установка `PyTorch`
1. Введение в `PyTorch`
1. Полносвязные слои и функции активации в `PyTorch`
1. Градиентный спуск своими руками

## Установка `PyTorch`

Мы будем использовать библиотеку для глубинного обучения `PyTorch`, ее можно не устанавливать, можно пользоваться сайтами [Kaggle](kaggle.com) и [Google Colab](colab.research.google.com/) для обучения в облаке (или с учителем?).

Чтобы установить `PyTorch` локально себе на компьютер нужно ответить на два вопроса - какая у вас операционная система и есть ли у вас дискретная видеокарта (GPU) и если есть, то какого производителя. В зависимости от ваших ответов мы получаем три варианта по операционной системе - Linux, Mac и Windows; три варианта по дискретной видеокарте - нет видеокарты (доступен только центральный процессор CPU), есть видеокарта от Nvidia или есть видеокарта от AMD (это производитель именно чипа, конечный вендор может быть другой, например, ASUS, MSI, Palit). Работа с PyTorch с видеокартой от AMD это экзотика, которая выходит за рамки нашего курса, поэтому рассмотрим только варианты *нет видеокарты*/*есть видеокарта от Nvidia*.


Выберите на [сайте](https://pytorch.org/get-started/locally/) подходящие вам варианты операционной системы/видеокарты и скопируйте команду для установки. Разберем подробно самые популярные варианты установки:

### Установка в Linux ([поддерживаемые дистрибутивы](https://pytorch.org/get-started/locally/#supported-linux-distributions))

На линуксе будет работать поддержка `PyTorch` в любой конфигурации, что у вас нет видеокарты, что есть от Nvidia, что от AMD.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.8 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).

### Установка в Windows

На винде будет работать поддержка `PyTorch` только для видеокарт от Nvidia и без видеокарт вообще.

Пререквизит для работы с видеокартой от Nvidia - нужно поставить CUDA, это инструмент от компании Nvidia, который позволяет ускорять вычисления на их же ГПУ. Чтобы поставить себе на машину все правильно воспользуйтесь этим [гайдом](https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html) от Nvidia.

 - **pip**

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu` для тех, у кого нет видеокарты.

`pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu118` для тех, у кого есть видеокарта (либо другой `--extra-index-url`, смотрите на сайте PyTorch, в зависимости от версии CUDA).

 - **conda**

`conda install pytorch torchvision torchaudio cpuonly -c pytorch` для тех, у кого нет видеокарты.

`conda install pytorch torchvision torchaudio cudatoolkit=11.8 -c pytorch -c conda-forge` для тех, у кого есть видеокарта (либо немного другая команда, в зависимости от версии CUDA).



### Установка на Mac

На маках есть поддержка `PyTorch` как на CPU, так и на GPU, но только для Apple Silicon, то есть на чипах M1, M2 и так далее.

При этом поддержка ускорения с помощью GPU есть только для версий макоси выше 12.3: MPS acceleration is available on MacOS 12.3+

 - **pip**

`pip3 install torch torchvision torchaudio`

 - **conda**

`conda install pytorch::pytorch torchvision torchaudio -c pytorch`

## Введение в `PyTorch`

### Тензоры

Тензоры — это специализированная структура данных, по сути это массивы и матрицы. Тензоры очень похожи на массивы в numpy, так что, если у вас хорошо с numpy, то разобраться в PyTorch тензорах будет очень просто. В PyTorch мы используем тензоры для кодирования входных и выходных данных модели, а также параметров модели.

In [1]:
import torch
import numpy as np

### Создание тензоров

Тензор можно создать напрямую из каких-то данных - нам подходят все списки с числами:

In [2]:
some_data = [1, 2, 3, 4]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([1, 2, 3, 4])

In [3]:
some_data = [[1, 2], [3, 4], [5, 6]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [4]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

some_tensor

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

На самом деле про "все" списки с числами - обман. Если у вашего списка есть какой-то уровень вложенности, то должны совпадать размерности у всех вложенных списков (подробнее про размерности поговорим позже):

In [7]:
some_other_data = [[1, 2, 2], [3, 4, 3], [5, 6, 7]]
some_other_tensor = torch.tensor(some_other_data)

some_other_tensor

tensor([[1, 2, 2],
        [3, 4, 3],
        [5, 6, 7]])

Также тензоры можно создавать из numpy массивов и наоборот:

In [8]:
some_numpy_array = np.array(some_data)

some_numpy_array

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]])

In [9]:
some_tensor_from_numpy = torch.from_numpy(some_numpy_array)

some_tensor_from_numpy

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [10]:
some_tensor_from_numpy2 = torch.tensor(some_numpy_array)

some_tensor_from_numpy2

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

При этом если мы создаем тензор из numpy массива с помощью `torch.from_numpy`, то они делят между собой память, где лежат их данные и, соответственно, при изменении тензора меняется numpy массив и наоборот:

In [11]:
x = np.ones(10)
y = torch.from_numpy(x)

x, y

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=torch.float64))

In [12]:
x += 1

x, y

(array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64))

In [13]:
x = torch.ones(10)
y = x.numpy()

x, y

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [14]:
x += 1

x, y

(tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.], dtype=float32))

Можем создать тензор со случайными или константными значениями:

In [15]:
shape = (2, 3)

random_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
empty_tensor = torch.empty(shape)

random_tensor, ones_tensor, zeros_tensor, empty_tensor

(tensor([[0.5020, 0.8882, 0.2101],
         [0.0626, 0.2358, 0.5213]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[ 1.2001e-04,  4.4989e-41, -6.1817e+14],
         [ 3.1176e-41, -6.1859e+14,  3.1176e-41]]))

Теперь поговорим про размерности подробнее.

У тензора есть какой-то размер, какая форма. Первое с чем нужно определиться, какой **размерности** тензор - количество осей у него.

In [16]:
shape = (10)  # одна ось (вектор)

tensor = torch.rand(shape)

tensor

tensor([0.0033, 0.5675, 0.8995, 0.0419, 0.3169, 0.1768, 0.2560, 0.4512, 0.8170,
        0.2204])

In [17]:
shape = (2, 3)  # две оси (матрица)

tensor = torch.rand(shape)

tensor

tensor([[0.4938, 0.6996, 0.9689],
        [0.9603, 0.9975, 0.8375]])

In [18]:
shape = (3, 2, 3)  # три оси (и больше - тензор)

tensor = torch.rand(shape)

tensor

tensor([[[0.5139, 0.2007, 0.8991],
         [0.9445, 0.0232, 0.5738]],

        [[0.6175, 0.8387, 0.8256],
         [0.6243, 0.2484, 0.8213]],

        [[0.5021, 0.1831, 0.5802],
         [0.6937, 0.9354, 0.1661]]])

Тензор с размерностью 1 - это просто вектор, список чисел.

Тензор с размерностью 2 - это просто матрица, то есть список списков чисел.

Тензор с размерностью 3 и больше - это тензор, то есть список списков списков ... чисел.

Получить доступ к размеру уже созданного тензора - метод `.shape`:

In [19]:
some_data = [[[1], [2]], [[3], [4]], [[5], [6]]]
some_tensor = torch.tensor(some_data)

print(some_tensor)
print(some_tensor.shape)

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])
torch.Size([3, 2, 1])


Давайте сделаем тензор, который будет нам имитировать изображение - сделаем его размер `(c, h, w)`, где `h` и `w` это его высота и ширина, а `c` - число каналов в цветовом пространстве (в черно-белом 1, в RGB 3):

In [20]:
h = 9
w = 16
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.2714, 0.3942, 0.6024, 0.1984, 0.3336, 0.9298, 0.6804, 0.3182,
          0.9971, 0.9165, 0.9516, 0.7354, 0.8254, 0.8935, 0.7312, 0.5043],
         [0.9521, 0.9171, 0.1355, 0.0163, 0.8630, 0.5652, 0.7886, 0.8597,
          0.5496, 0.9999, 0.2493, 0.4236, 0.0227, 0.1431, 0.2521, 0.7201],
         [0.9904, 0.1542, 0.8009, 0.4985, 0.4986, 0.8771, 0.7393, 0.6964,
          0.4834, 0.2854, 0.2868, 0.5420, 0.1837, 0.8382, 0.0535, 0.7384],
         [0.3735, 0.2536, 0.7488, 0.2254, 0.5757, 0.3942, 0.1603, 0.7055,
          0.8470, 0.0148, 0.3477, 0.1777, 0.9720, 0.6953, 0.5521, 0.0586],
         [0.7047, 0.3783, 0.1608, 0.6760, 0.1270, 0.5314, 0.8061, 0.2268,
          0.1670, 0.0758, 0.4903, 0.8417, 0.3904, 0.2749, 0.6775, 0.7217],
         [0.7776, 0.1444, 0.4043, 0.4616, 0.5232, 0.1534, 0.9069, 0.0823,
          0.7387, 0.4801, 0.5650, 0.2816, 0.3545, 0.5296, 0.8346, 0.4302],
         [0.7769, 0.2256, 0.7087, 0.8330, 0.8943, 0.6731, 0.8971, 0.1354,
          0.7379, 0.4605, 0.8936

In [21]:
image_tensor.shape

torch.Size([3, 9, 16])

Можем попробовать поменять размер тензора, например, [вытянуть его в вектор](https://pytorch.org/docs/stable/generated/torch.ravel.html):

In [22]:
image_tensor.flatten()

tensor([0.2714, 0.3942, 0.6024, 0.1984, 0.3336, 0.9298, 0.6804, 0.3182, 0.9971,
        0.9165, 0.9516, 0.7354, 0.8254, 0.8935, 0.7312, 0.5043, 0.9521, 0.9171,
        0.1355, 0.0163, 0.8630, 0.5652, 0.7886, 0.8597, 0.5496, 0.9999, 0.2493,
        0.4236, 0.0227, 0.1431, 0.2521, 0.7201, 0.9904, 0.1542, 0.8009, 0.4985,
        0.4986, 0.8771, 0.7393, 0.6964, 0.4834, 0.2854, 0.2868, 0.5420, 0.1837,
        0.8382, 0.0535, 0.7384, 0.3735, 0.2536, 0.7488, 0.2254, 0.5757, 0.3942,
        0.1603, 0.7055, 0.8470, 0.0148, 0.3477, 0.1777, 0.9720, 0.6953, 0.5521,
        0.0586, 0.7047, 0.3783, 0.1608, 0.6760, 0.1270, 0.5314, 0.8061, 0.2268,
        0.1670, 0.0758, 0.4903, 0.8417, 0.3904, 0.2749, 0.6775, 0.7217, 0.7776,
        0.1444, 0.4043, 0.4616, 0.5232, 0.1534, 0.9069, 0.0823, 0.7387, 0.4801,
        0.5650, 0.2816, 0.3545, 0.5296, 0.8346, 0.4302, 0.7769, 0.2256, 0.7087,
        0.8330, 0.8943, 0.6731, 0.8971, 0.1354, 0.7379, 0.4605, 0.8936, 0.5584,
        0.6813, 0.4227, 0.1282, 0.0280, 

In [23]:
image_tensor.ravel().shape

torch.Size([432])

In [ ]:
h * w * c

432

Посчитаем количество элементов в тензоре с помощью [специальной функции](https://pytorch.org/docs/stable/generated/torch.numel.html):

In [24]:
image_tensor.numel()

432

In [26]:
h = 2
w = 3
c = 3

shape = (c, h, w)

image_tensor = torch.rand(shape)

image_tensor

tensor([[[0.4387, 0.1270, 0.2344],
         [0.6434, 0.9684, 0.0746]],

        [[0.3619, 0.8208, 0.4429],
         [0.6603, 0.1609, 0.0431]],

        [[0.6922, 0.1262, 0.0545],
         [0.6789, 0.4641, 0.8964]]])

Попробуем поменять размер с помощью функции [reshape](https://pytorch.org/docs/stable/generated/torch.reshape.html#torch.reshape):

In [28]:
image_tensor.reshape(c, h * w)

tensor([[0.4387, 0.1270, 0.2344, 0.6434, 0.9684, 0.0746],
        [0.3619, 0.8208, 0.4429, 0.6603, 0.1609, 0.0431],
        [0.6922, 0.1262, 0.0545, 0.6789, 0.4641, 0.8964]])

Попробуем собрать из нескольких тензоров один большой:

[torch.cat](https://pytorch.org/docs/stable/generated/torch.cat.html#torch.cat)

In [46]:
x = torch.randn(2, 3)

In [47]:
x

tensor([[-1.0400, -0.4065,  0.0712],
        [-1.8094,  0.7606,  0.4254]])

In [48]:
torch.cat((x, x, x), dim=0)

tensor([[-1.0400, -0.4065,  0.0712],
        [-1.8094,  0.7606,  0.4254],
        [-1.0400, -0.4065,  0.0712],
        [-1.8094,  0.7606,  0.4254],
        [-1.0400, -0.4065,  0.0712],
        [-1.8094,  0.7606,  0.4254]])

In [49]:
torch.stack((x, x, x, x), dim=0).shape

torch.Size([4, 2, 3])

In [61]:
x = torch.randn(2, 3)

x.shape

torch.Size([2, 3])

In [62]:
x.unsqueeze_(0).shape

torch.Size([1, 2, 3])

In [64]:
x = torch.randn(3, 3, 2)
y = torch.randn(5, 3, 2)
z = torch.randn(1, 3, 2)

for tensor in [x, y, z]:
    print(tensor)

torch.cat((x, y, z), dim=0).shape

tensor([[[ 0.0693, -0.2600],
         [-0.1902, -1.0753],
         [ 0.0795, -1.7049]],

        [[-0.2401, -0.4854],
         [-0.2019,  0.2350],
         [-0.0951, -1.2066]],

        [[-0.4911, -0.0298],
         [ 1.4034,  1.4224],
         [ 1.4632, -1.0498]]])
tensor([[[ 0.3150,  0.3492],
         [-0.3393,  0.5618],
         [-1.4872,  0.2026]],

        [[ 0.4408,  0.9498],
         [ 1.2430, -0.6430],
         [ 0.9079, -1.2596]],

        [[ 0.3355,  1.3064],
         [ 0.2997,  0.8560],
         [ 0.6259,  0.3693]],

        [[ 0.1782, -2.0297],
         [ 0.0241, -0.9646],
         [ 0.1982, -1.1038]],

        [[ 0.0034,  0.1950],
         [-0.9092, -0.6835],
         [-1.2932, -0.3836]]])
tensor([[[-1.5554,  1.5635],
         [ 1.1089,  0.4812],
         [-1.1143, -0.8398]]])


torch.Size([9, 3, 2])

In [65]:
x = torch.randn(2, 3)
y = torch.randn(2, 5)
z = torch.randn(2, 1)

for tensor in [x, y, z]:
    print(tensor)

torch.stack((x, x, x), dim=0)

tensor([[-0.2810,  0.2168, -0.3585],
        [ 0.0260, -3.1892, -0.3808]])
tensor([[-1.2021,  0.6363, -1.4840, -0.0327,  0.9261],
        [ 1.8543,  0.6393,  1.2229,  1.6472,  0.8591]])
tensor([[-1.0346],
        [-0.0228]])


tensor([[[-0.2810,  0.2168, -0.3585],
         [ 0.0260, -3.1892, -0.3808]],

        [[-0.2810,  0.2168, -0.3585],
         [ 0.0260, -3.1892, -0.3808]],

        [[-0.2810,  0.2168, -0.3585],
         [ 0.0260, -3.1892, -0.3808]]])

Теперь добавим дополнительную ось:

[torch.unsqueeze](https://pytorch.org/docs/stable/generated/torch.unsqueeze.html)

In [66]:
x = torch.rand(2, 3)

print(x)
print()
print(x.unsqueeze(0), x.unsqueeze(0).shape)
print()
print(x.unsqueeze(1), x.unsqueeze(1).shape)
print()
print(x.unsqueeze(2), x.unsqueeze(2).shape)

tensor([[0.6224, 0.4959, 0.8065],
        [0.8786, 0.0425, 0.9076]])

tensor([[[0.6224, 0.4959, 0.8065],
         [0.8786, 0.0425, 0.9076]]]) torch.Size([1, 2, 3])

tensor([[[0.6224, 0.4959, 0.8065]],

        [[0.8786, 0.0425, 0.9076]]]) torch.Size([2, 1, 3])

tensor([[[0.6224],
         [0.4959],
         [0.8065]],

        [[0.8786],
         [0.0425],
         [0.9076]]]) torch.Size([2, 3, 1])


Уберем лишние оси (где размер единичка):

In [67]:
x = torch.rand(1, 2, 1, 3)

print(x)
print()
print(x.squeeze(), x.squeeze().shape)
print()
print(x.squeeze(1), x.squeeze(1).shape)

tensor([[[[0.3129, 0.1951, 0.8415]],

         [[0.2055, 0.4938, 0.8077]]]])

tensor([[0.3129, 0.1951, 0.8415],
        [0.2055, 0.4938, 0.8077]]) torch.Size([2, 3])

tensor([[[[0.3129, 0.1951, 0.8415]],

         [[0.2055, 0.4938, 0.8077]]]]) torch.Size([1, 2, 1, 3])


Теперь поговорим про типы данных в тензорах. По умолчанию в тензорах лежат числа в torch.float32 для вещественных и torch.int64 для целочисленных.

In [68]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9])

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000])

In [69]:
tensor.dtype

torch.float32

In [70]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float16)

tensor

tensor([1.5000, 2.1992, 3.6992, 4.8984], dtype=torch.float16)

In [71]:
tensor = torch.tensor([1.5, 2.2, 3.7, 4.9], dtype=torch.float64)

tensor

tensor([1.5000, 2.2000, 3.7000, 4.9000], dtype=torch.float64)

In [72]:
tensor = torch.tensor([15, 22, 37, 49])

tensor

tensor([15, 22, 37, 49])

In [73]:
tensor.dtype

torch.int64

In [74]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int32)

tensor

tensor([15, 22, 37, 49], dtype=torch.int32)

In [75]:
tensor = torch.tensor([15, 22, 37, 49], dtype=torch.int16)

tensor

tensor([15, 22, 37, 49], dtype=torch.int16)

Размещение тензора на GPU:

In [76]:
print(torch.cuda.is_available())
print(torch.cuda.get_device_name())

True
Tesla T4


In [77]:
! nvidia-smi

Sun Nov  3 16:16:58 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [78]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)

cuda:0


In [79]:
tensor = torch.tensor([15, 22, 37, 49], device=device)

tensor

tensor([15, 22, 37, 49], device='cuda:0')

In [81]:
tensor = torch.tensor([15, 22, 37, 49])

print(tensor)

tensor = tensor.to(device)

tensor

tensor([15, 22, 37, 49])


tensor([15, 22, 37, 49], device='cuda:0')

In [82]:
tensor.to(torch.int32)

tensor([15, 22, 37, 49], device='cuda:0', dtype=torch.int32)

In [83]:
tensor = tensor.cpu()

tensor

tensor([15, 22, 37, 49])

In [84]:
tensor.cuda()

tensor([15, 22, 37, 49], device='cuda:0')

In [85]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a + b

tensor([[1.5640, 0.6864, 1.7213],
        [0.7345, 1.2089, 0.5882]])

In [86]:
a = a.to(device)

a + b

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

In [87]:
b = b.to(device)

a + b

tensor([[1.5640, 0.6864, 1.7213],
        [0.7345, 1.2089, 0.5882]], device='cuda:0')

### Операции с тензорами

Большая часть операций с тензорами хорошо описана в их [документации](https://pytorch.org/docs/stable/torch.html), разберем основные:

In [88]:
a = torch.rand(2, 3)
b = torch.rand(2, 3)

a, b

(tensor([[0.6009, 0.4247, 0.2935],
         [0.3876, 0.7189, 0.4851]]),
 tensor([[0.0596, 0.9913, 0.1528],
         [0.2120, 0.9314, 0.4532]]))

In [89]:
# поэлементные

print(a + b)

print()

print(torch.add(a, b))

print()

print(a.add(b))

tensor([[0.6605, 1.4160, 0.4463],
        [0.5996, 1.6504, 0.9383]])

tensor([[0.6605, 1.4160, 0.4463],
        [0.5996, 1.6504, 0.9383]])

tensor([[0.6605, 1.4160, 0.4463],
        [0.5996, 1.6504, 0.9383]])


In [90]:
print(a - b)

print()

print(torch.sub(a, b))

print()

print(a.sub(b))

tensor([[ 0.5413, -0.5666,  0.1407],
        [ 0.1756, -0.2125,  0.0318]])

tensor([[ 0.5413, -0.5666,  0.1407],
        [ 0.1756, -0.2125,  0.0318]])

tensor([[ 0.5413, -0.5666,  0.1407],
        [ 0.1756, -0.2125,  0.0318]])


In [91]:
print(a * b)

print()

print(torch.mul(a, b))

print()

print(a.mul(b))

tensor([[0.0358, 0.4210, 0.0448],
        [0.0822, 0.6696, 0.2198]])

tensor([[0.0358, 0.4210, 0.0448],
        [0.0822, 0.6696, 0.2198]])

tensor([[0.0358, 0.4210, 0.0448],
        [0.0822, 0.6696, 0.2198]])


In [92]:
print(a / b)

print()

print(torch.div(a, b))

print()

print(a.div(b))

tensor([[10.0853,  0.4284,  1.9210],
        [ 1.8283,  0.7719,  1.0702]])

tensor([[10.0853,  0.4284,  1.9210],
        [ 1.8283,  0.7719,  1.0702]])

tensor([[10.0853,  0.4284,  1.9210],
        [ 1.8283,  0.7719,  1.0702]])


In [93]:
a = torch.rand(2, 3)
b = torch.rand(3, 4)
c = torch.rand(5, 5)

a, b, c

(tensor([[0.3999, 0.6247, 0.0458],
         [0.8577, 0.8608, 0.3346]]),
 tensor([[0.2014, 0.2702, 0.9009, 0.2525],
         [0.6835, 0.8665, 0.1272, 0.9652],
         [0.7454, 0.1738, 0.5471, 0.3331]]),
 tensor([[0.6004, 0.2734, 0.1423, 0.3446, 0.0226],
         [0.1344, 0.9968, 0.0348, 0.6236, 0.3044],
         [0.3527, 0.1596, 0.4537, 0.6365, 0.3354],
         [0.1075, 0.7240, 0.7287, 0.8468, 0.4543],
         [0.2339, 0.5326, 0.4105, 0.4988, 0.8752]]))

In [94]:
# матричные операции

print(a @ b, (a @ b).shape)

print()

print(torch.matmul(a, b), torch.matmul(a, b).shape)

print()

print(c.trace())

print()

print(c.exp())

tensor([[0.5417, 0.6573, 0.4649, 0.7192],
        [1.0105, 1.0358, 1.0654, 1.1589]]) torch.Size([2, 4])

tensor([[0.5417, 0.6573, 0.4649, 0.7192],
        [1.0105, 1.0358, 1.0654, 1.1589]]) torch.Size([2, 4])

tensor(3.7729)

tensor([[1.8228, 1.3144, 1.1530, 1.4114, 1.0229],
        [1.1438, 2.7096, 1.0354, 1.8656, 1.3558],
        [1.4230, 1.1730, 1.5741, 1.8898, 1.3985],
        [1.1135, 2.0626, 2.0723, 2.3322, 1.5751],
        [1.2635, 1.7034, 1.5075, 1.6468, 2.3994]])
